# 请求参数
uint16_t catcher_motor_pwm      #吸尘电机占空比：0 - 1000；
uint8_t  catcher_gear          #吸尘电机档位：2高 1中 0低
uint8_t  catcher_state        #吸尘电机控制：1开 0关
---
# 响应结果
bool success       # 是否执行成功
string message     # 详细信息